server:
  port: 8080
spring:
  application:
    name: edge-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
        - id: api-registry-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/apis/**


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
